### ISSUE TITLE
Wrong with TwoSum.java

### ISSUE THREAD

**Issue by kennedy-han** [leetcoders/LeetCode-Java#1]
please check your code

Your input

[2, 7, 11, 15]
9
Your answer

[1,2]
Expected answer

[0,1]

**Comment by ManavTanna** [comment]
class Solution {
    public int[] twoSum(int[] nums, int target) {
       
        HashMap<Integer,Integer> map = new HashMap<>();
        for(int i=0;i<nums.length;i++){
            map.put(nums[i], i);
        }
        int sol [] =new int[2];
        for(int i=0;i<nums.length;i++){
            if(map.containsKey(target-nums[i]) && i!=map.get(target-nums[i])){
                sol[0]=i;
                sol[1]=map.get(target-nums[i]);
                break;
            }
        }
        return sol;
    }
}

Here's the updated version of the code which will give the correct output

**Comment by kennedy-han** [comment]
cool.
